name: 扫描目录并保存图像路径-py
on:
  schedule:
    - cron: '0 3 * * 0'  # 每周日的3点执行
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: '手动启动'
        default: 'false'

jobs:
  scan_images:
    runs-on: ubuntu-latest

    env:
      REPO_OWNER: songwqs   #用户
      REPO_NAME: cdnImg     #仓库
      PATH_TO_SCAN: hacg    #目录
      OUTPUT_FILE: image_paths.json  #'保存格式'

    steps:
      - name: 签出 songw_Actions 存储库
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}
          path: songw_Actions

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 安装依赖项
        run: |
          cd songw_Actions
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行 Python 脚本
        run: |
          cd songw_Actions
          python python/scan_directory.py
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_2 }}
          PATH_TO_SCAN: ${{ env.PATH_TO_SCAN }}
          OUTPUT_FILE: ${{ env.OUTPUT_FILE }}

      - name: 拉取 cdnImg 仓库的更改
        run: |
          cd songw_Actions/cdnImg
          git pull origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 移动 image_paths.json 文件
        run: mv songw_Actions/image_paths.json songw_Actions/cdnImg/hacg/

      - name: 切换到 songw_Actions/cdnImg 目录
        run: cd songw_Actions/cdnImg

      - name: 列出当前目录下的子目录
        run: ls -d */ | grep '/'

      - name: 提交更改到 cdnImg 仓库
        run: |
          cd songw_Actions/cdnImg/hacg
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@gmail.com"
          git add .
          git commit -m "Update image paths"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          git push origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
