name: 扫描目录并保存图像路径-py
on:
  schedule:
    - cron: '0 3 * * 0'  # 每周日的3点执行
  workflow_dispatch:
    # 为手动触发提供一个可选的输入参数
    inputs:
      manual_trigger:
        description: '手动启动'
        default: 'false'

jobs:
  scan_images:
    runs-on: ubuntu-latest
    env:
      REP_NAME: ${{ github.event.repository.name }}  #'当前仓库名字'
      REPO_OWNER: songwqs   #用户
      REPO_NAME: cdnImg     #仓库
      PATH_TO_SCAN: hacg    #目录
      OUTPUT_FILE: image_paths.json  #'json名字'
      
    steps:
      - name: 签出 songw_Actions 存储库
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_OWNER }}/songw_Actions
          path: songw_Actions
      - name: 创建 ${{ env.PATH_TO_SCAN }} 目录
        run: mkdir -p songw_Actions/${{ env.REPO_NAME }}/${{ env.PATH_TO_SCAN }}
        
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 安装依赖项
        run: |
          cd songw_Actions
          python -m pip install --upgrade pip
          pip install requests
      - name: 运行 Python 脚本
        run: |
          cd songw_Actions
          python python/scan_directory.py
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_2 }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          REPO_NAME: ${{ env.REPO_NAME }}
          PATH_TO_SCAN: ${{ env.PATH_TO_SCAN }}
          OUTPUT_FILE: ${{ env.OUTPUT_FILE }}
      
      - name: 拉取 ${{ env.REPO_NAME }} 仓库的更改
        run: |
          cd songw_Actions/${{ env.REPO_NAME }}
          git pull origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: 移动 image_paths.json 文件
        run: mv songw_Actions/image_paths.json songw_Actions/${{ env.REPO_NAME }}/${{ env.PATH_TO_SCAN }}/
        
      - name: 切换到 songw_Actions/${{ env.REPO_NAME }} 目录
        run: cd songw_Actions/${{ env.REPO_NAME }}

      - name: 打印当前工作目录
        run: pwd
        
      - name: 列出当前目录下的子目录
        run: |
          cd songw_Actions/${{ env.REPO_NAME }}
          ls -d */ | grep '/'
        
      - name: Push changes to ${{ env.REPO_NAME }} repository
        run: |
          cd songw_Actions/${{ env.REPO_NAME }}/${{ env.PATH_TO_SCAN }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@gmail.com"
          git add .
          git commit -m "Update image paths"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          git push origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
